### ISSUE TITLE
Invalid Ruby version lock

### ISSUE THREAD

**Issue by mensfeld** [ractor-tools/ractor-server#1]
Hey there,
Just wanted to let you know, that while this lib uses `::Ractor` the minimum requirement in RubyGems is not 3.0 but 2.3. Is that intended?

**Comment by marcandre** [comment]
It isn't!
I'd like to make it 2.3+ compatible with `ruby-next` + my Ractor backport, but haven't had time to do that yet.
So thanks, I'll fix it.
I've not announced this gem yet, surprised to have feedback. Let me know what you think and your experiences if you use it.

**Comment by mensfeld** [comment]
> I've not announced this gem yet, surprised to have feedback.

Aaa you see :) I run the security project called https://diffend.io and things you do in this lib caught its attention ;)

> Let me know what you think and your experiences if you use it.

I do not :( I analyze the sources looking for vulnerabilities and potential security flaws although I plan to give it a shot :)

Since I got an answer I will close the card. Thank you :pray:

**Comment by marcandre** [comment]
v.0.1.1 released, 0.1.0 yanked.

**Comment by mensfeld** [comment]
https://my.diffend.io/gems/ractor-server/0.1.0/0.1.1#d2h-004177-816 :pray:
